=== precise-alloy/precise-alloy/PreciseAlloy.Frontend/packages/x-pkg/xpack/states.schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "name": {
      "type": "string"
    },
    "selector": {
      "type": "string"
    },
    "button": {
      "type": "object",
      "properties": {
        "parentSelector": {
          "type": "string"
        },
        "styleModifier": {
          "type": "string"
        },
        "zIndex": {
          "type": "integer"
        }
      }
    },
    "states": {
      "type": "array",
      "items": [
        {
          "type": "object",
          "properties": {
            "name": {
              "type": "string"
            },
            "options": {
              "type": "array",
              "items": [
                {
                  "type": "object",
                  "properties": {
                    "value": {
                      "type": "string"
                    },
                    "name": {
                      "type": "string"
                    }
                  },
                  "required": ["name"]
                }
              ]
            },
            "multiple": {
              "type": "boolean"
            }
          },
          "required": ["name"]
        }
      ]
    }
  },
  "required": ["name", "selector", "states"]
}

=== precise-alloy/precise-alloy/PreciseAlloy.Frontend/packages/x-pkg/src/organisms/teaser/Teaser.states.json
{
  "name": "Teaser",
  "selector": ".zzz-o-teaser",
  "button": {
    "parentSelector": ".zzz-o-teaser__inner",
    "styleModifier": "pl-state--top-right"
  },
  "states": [
    {
      "name": "Image position",
      "multiple": false,
      "options": [
        {
          "value": "zzz-o-teaser--image-left",
          "name": "Left"
        },
        {
          "value": "zzz-o-teaser--image-right",
          "name": "Right"
        }
      ]
    }
  ]
}

=== precise-alloy/precise-alloy/PreciseAlloy.Frontend/packages/x-pkg/public/pl-states.json
[
  {
    "name": "Contact",
    "selector": ".zzz-o-contact",
    "button": {
      "parentSelector": ".zzz-o-contact__main",
      "styleModifier": "pl-state--top-right"
    },
    "states": [
      {
        "name": "Map position",
        "multiple": false,
        "options": [
          {
            "value": "zzz-o-contact--map-left",
            "name": "Left"
          },
          {
            "value": "zzz-o-contact--map-right",
            "name": "Right"
          }
        ]
      }
    ]
  },
  {
    "name": "Teaser",
    "selector": ".zzz-o-teaser",
    "button": {
      "parentSelector": ".zzz-o-teaser__inner",
      "styleModifier": "pl-state--top-right"
    },
    "states": [
      {
        "name": "Image position",
        "multiple": false,
        "options": [
          {
            "value": "zzz-o-teaser--image-left",
            "name": "Left"
          },
          {
            "value": "zzz-o-teaser--image-right",
            "name": "Right"
          }
        ]
      }
    ]
  }
]

=== precise-alloy/precise-alloy/PreciseAlloy.Frontend/packages/x-pkg/src/organisms/contact/Contact.states.json
{
  "name": "Contact",
  "selector": ".zzz-o-contact",
  "button": {
    "parentSelector": ".zzz-o-contact__main",
    "styleModifier": "pl-state--top-right"
  },
  "states": [
    {
      "name": "Map position",
      "multiple": false,
      "options": [
        {
          "value": "zzz-o-contact--map-left",
          "name": "Left"
        },
        {
          "value": "zzz-o-contact--map-right",
          "name": "Right"
        }
      ]
    }
  ]
}
